# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import task_manager_pb2 as task__manager__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in task_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskManagerStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTask = channel.unary_unary(
                '/task_manager.TaskManager/AddTask',
                request_serializer=task__manager__pb2.AddTaskRequest.SerializeToString,
                response_deserializer=task__manager__pb2.AddTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/task_manager.TaskManager/ListTasks',
                request_serializer=task__manager__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=task__manager__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/task_manager.TaskManager/CompleteTask',
                request_serializer=task__manager__pb2.CompleteTaskRequest.SerializeToString,
                response_deserializer=task__manager__pb2.CompleteTaskResponse.FromString,
                _registered_method=True)


class TaskManagerServicer(object):
    """Define the service
    """

    def AddTask(self, request, context):
        """Add a new task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """List all tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Mark a task as completed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTask,
                    request_deserializer=task__manager__pb2.AddTaskRequest.FromString,
                    response_serializer=task__manager__pb2.AddTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=task__manager__pb2.ListTasksRequest.FromString,
                    response_serializer=task__manager__pb2.ListTasksResponse.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=task__manager__pb2.CompleteTaskRequest.FromString,
                    response_serializer=task__manager__pb2.CompleteTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'task_manager.TaskManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('task_manager.TaskManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskManager(object):
    """Define the service
    """

    @staticmethod
    def AddTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task_manager.TaskManager/AddTask',
            task__manager__pb2.AddTaskRequest.SerializeToString,
            task__manager__pb2.AddTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task_manager.TaskManager/ListTasks',
            task__manager__pb2.ListTasksRequest.SerializeToString,
            task__manager__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/task_manager.TaskManager/CompleteTask',
            task__manager__pb2.CompleteTaskRequest.SerializeToString,
            task__manager__pb2.CompleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
