# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task_manager.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task_manager.proto\x12\x0ctask_manager\"I\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\"4\n\x0e\x41\x64\x64TaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"3\n\x0f\x41\x64\x64TaskResponse\x12 \n\x04task\x18\x01 \x01(\x0b\x32\x12.task_manager.Task\"\x12\n\x10ListTasksRequest\"6\n\x11ListTasksResponse\x12!\n\x05tasks\x18\x01 \x03(\x0b\x32\x12.task_manager.Task\"!\n\x13\x43ompleteTaskRequest\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x14\x43ompleteTaskResponse\x12 \n\x04task\x18\x01 \x01(\x0b\x32\x12.task_manager.Task2\xfa\x01\n\x0bTaskManager\x12\x46\n\x07\x41\x64\x64Task\x12\x1c.task_manager.AddTaskRequest\x1a\x1d.task_manager.AddTaskResponse\x12L\n\tListTasks\x12\x1e.task_manager.ListTasksRequest\x1a\x1f.task_manager.ListTasksResponse\x12U\n\x0c\x43ompleteTask\x12!.task_manager.CompleteTaskRequest\x1a\".task_manager.CompleteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=36
  _globals['_TASK']._serialized_end=109
  _globals['_ADDTASKREQUEST']._serialized_start=111
  _globals['_ADDTASKREQUEST']._serialized_end=163
  _globals['_ADDTASKRESPONSE']._serialized_start=165
  _globals['_ADDTASKRESPONSE']._serialized_end=216
  _globals['_LISTTASKSREQUEST']._serialized_start=218
  _globals['_LISTTASKSREQUEST']._serialized_end=236
  _globals['_LISTTASKSRESPONSE']._serialized_start=238
  _globals['_LISTTASKSRESPONSE']._serialized_end=292
  _globals['_COMPLETETASKREQUEST']._serialized_start=294
  _globals['_COMPLETETASKREQUEST']._serialized_end=327
  _globals['_COMPLETETASKRESPONSE']._serialized_start=329
  _globals['_COMPLETETASKRESPONSE']._serialized_end=385
  _globals['_TASKMANAGER']._serialized_start=388
  _globals['_TASKMANAGER']._serialized_end=638
# @@protoc_insertion_point(module_scope)
